# Generated by Django 5.0 on 2023-12-12 14:07

import shelterblog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='file',
            field=models.FileField(blank=True, upload_to=shelterblog.models.user_directory_path),
        ),
    ]
