# Generated by Django 4.2.7 on 2023-12-06 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petlistings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Pending', 'Pending'), ('Adopted', 'Withdrawn')], default='Pending', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petlistings.petlisting')),
                ('pet_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seeker')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter')),
            ],
        ),
    ]
