# Generated by Django 4.2.7 on 2023-12-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('denied', 'Denied'), ('pending', 'Pending'), ('adopted', 'Withdrawn')], default='pending', max_length=8),
        ),
    ]
