# Generated by Django 4.2.6 on 2023-11-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('about', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('shelter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to='accounts.shelter')),
            ],
        ),
    ]
