# Generated by Django 4.2.6 on 2023-11-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('petlistings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to='accounts.shelter'),
        ),
    ]
